openapi: 3.0.0
info:
  title: MyJYU library card api
  version: '1.0.0'
paths:
  /test:
    post:
      description: Echo back the request body to test type coercion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                age:
                  type: integer
                isCool:
                  type: boolean
                  x-openapi-coercion-strict: true
      responses:
        200:
          description: An echo of the request body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  age:
                    type: integer
                  isCool:
                    type: boolean
