openapi: 3.0.0
info:
  title: MyJYU library card api
  version: '1.0.0'
paths:
  /card:
    post:
      description: Create new patron to library information sytem Koha
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                address:
                  type: string
                postal_code:
                  type: string
                city:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                pin1:
                  type: string
                pin2:
                  type: string
                  x-openapi-coercion-strict: true
      responses:
        200:
          description: An echo of the request body.
        # virheresponset