openapi: 3.0.0
info:
  title: MyJYU library card api
  version: '1.0.0'
paths:
  /card:
    get:
      description: Get user's library card number
      responses:
        200:
          description: Library card number
          content:
            application/json:
              schema:
                type: object
                properties:
                  cardnumber:
                    type: string
        400:
          description: Default response
        401:
          description: Authentication required
        403:
          description: Access forbidden
        404:
          description: Resource not found
        500:
          description: Internal server error
        501:
          description: Default response
    post:
      description: Create new patron to library information sytem Koha
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - address
                - postal_code
                - city
                - email
                - phone
                - pin1
                - pin2
              properties:
                address:
                  type: string
                postal_code:
                  type: string
                city:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                pin1:
                  type: string
                  description: Only numerical values accepted, 4 digits minimum
                pin2:
                  type: string
                  description: Only numerical values accepted, 4 digits minimum
              x-openapi-coercion-strict: true
      responses:
        201:
          description: Library card created
          content:
            application/json:
              schema:
                type: object
                properties:
                  patron_id:
                    type: integer
                  cardnumber:
                    type: string
        400:
          description: Bad parameter
        401:
          description: Authentication required
        403:
          description: Access forbidden
        404:
          description: Resource not found
        409:
          description: Card with given SSN already exists
        500:
          description: Internal server error
        501:
          description: Default response
        503:
          description: Under maintenance
  /card/{patron_id}:
    delete:
      description: Delete patron from library system Koha, for testing purposes only!
      parameters:
        - in: path
          name: patron_id
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Patron deleted
        400:
          description: Patron deletion failed
        401:
          description: Authentication required
        403:
          description: Access forbidden
        404:
          description: Patron not found
        500:
          description: Default response
        501:
          description: Default response
  /card/pin:
    post:
      description: Change card's pin code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - pin1
                - pin2
              properties:
                pin1:
                  type: string
                  description: Only numerical values accepted, 4 digits minimum
                pin2:
                  type: string
                  description: Only numerical values accepted, 4 digits minimum
              x-openapi-coercion-strict: true
      responses:
        200:
          description: Pin code changed
        400:
          description: Bad request
        401:
          description: Authentication required
        403:
          description: Access forbidden
        404:
          description: Patron not found
        500:
          description: Internal server error
        501:
          description: Default response
        503:
          description: Under maintenance

        

